version: 2
updates:
  - package-ecosystem: npm
    directory: "/firefox-extension"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "[dependabot]"
  - package-ecosystem: npm
    directory: "/node-readability"
    schedule:
      interval: "weekly"
      day: "thursday"
    commit-message:
      prefix: "[dependabot]"
  - package-ecosystem: composer
    directory: "/symfony-app"
    schedule:
      interval: weekly
      day: "thursday"
    commit-message:
      prefix: "[dependabot]"

  - package-ecosystem: "docker"
    directory: "/symfony-app"
    schedule:
      interval: weekly
      day: "thursday"
    commit-message:
      prefix: "[dependabot]"
  - package-ecosystem: "docker"
    directory: "/node-readability"
    schedule:
      interval: weekly
      day: "thursday"
    commit-message:
      prefix: "[dependabot]"
