version: 2
updates:
  - package-ecosystem: npm
    directory: "/firefox-extension"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
      prefix-development: "[dependabot-dev]"
    open-pull-requests-limit: 10
    groups:
      firefox-extension-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "/node-readability"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
      prefix-development: "[dependabot-dev]"
    open-pull-requests-limit: 10
    groups:
      node-readability-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: composer
    directory: "/symfony-app"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
      prefix-development: "[dependabot-dev]"
    open-pull-requests-limit: 50
    groups:
      app-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: "/go-readability-api"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
      prefix-development: "[dependabot-dev]"
    open-pull-requests-limit: 10
    groups:
      go-readability-api-dependencies:
        applies-to: version-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/symfony-app"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
  - package-ecosystem: "docker"
    directory: "/node-readability"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
  - package-ecosystem: "docker"
    directory: "/go-readability-api"
    schedule:
      interval: weekly
      day: "monday"
    commit-message:
      prefix: "[dependabot]"
