version: '3.4'
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    volumes:
      - ./symfony-app:/app
  php:
    build:
      context: ./symfony-app
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=1
    volumes:
      - ./symfony-app:/app
    environment:
      XDEBUG_TRIGGER: "default_no_matter"
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: "client_host=${MY_IP:-172.17.0.1} discover_client_host=0 client_port=9000"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME:-webpage2content}"
  worker-new-job:
    build:
      context: ./symfony-app
      dockerfile: Dockerfile
    volumes:
      - ./symfony-app:/app
    depends_on:
      - rabbitmq
    command: [ "/app/bin/wait-for-it.sh", "rabbitmq:5672", "--", "php", "-d", "apc.enable_cli=1", "/app/bin/console", "rabbitmq:consume", "-m", "10", "new_job" ]
  worker-fetch-page-content:
    build:
      context: ./symfony-app
      dockerfile: Dockerfile
    volumes:
      - ./symfony-app:/app
    depends_on:
      - rabbitmq
    command: [ "/app/bin/wait-for-it.sh", "rabbitmq:5672", "--", "php", "-d", "apc.enable_cli=1", "/app/bin/console", "rabbitmq:consume", "-m", "10", "fetch_page_content" ]
  worker-create-url:
    build:
      context: ./symfony-app
      dockerfile: Dockerfile
    volumes:
      - ./symfony-app:/app
    depends_on:
      - rabbitmq
    command: [ "/app/bin/wait-for-it.sh", "rabbitmq:5672", "--", "php", "-d", "apc.enable_cli=1", "/app/bin/console", "rabbitmq:consume", "-m", "10", "push_to_kindle_url" ]
  node:
    build:
      context: ./node-readability
      dockerfile: Dockerfile-dev
    volumes:
      - ./node-readability:/app
    command: [ "npx", "ts-node-dev", "/app/microservice.ts" ]
  rabbitmq:
    image: rabbitmq:3.9.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
  go-readability-api:
    build:
      context: ./go-readability-api
      dockerfile: Dockerfile
    command:
      - --http
      - :8080
  redis:
      image: redis:7.0-alpine
  redis-web:
      image: rediscommander/redis-commander:latest
      environment:
          - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"
