version: '3.4'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    command: ["php", "-S", "0.0.0.0:4200", "-t", "/app/public"]
    ports:
      - "4200:4200"
