version: '3.4'
services:
  php:
    build:
      context: ./symfony-app
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=1
    volumes:
      - ./symfony-app:/app
      - ./symfony-app/Caddyfile:/etc/Caddyfile
    ports:
      - "4200:80"
    environment:
      SERVER_NAME: "http://localhost:80 http://127.0.0.1:80"
      XDEBUG_TRIGGER: "default_no_matter"
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: "client_host=${MY_IP:-172.17.0.1} discover_client_host=0 client_port=9000"
      PHP_IDE_CONFIG: "serverName=${DEV_SERVER_NAME:-webpage2kindle}"
      MERCURE_PUBLISHER_JWT_KEY: "!publisherKeyOnlyForDevSomePaddingToFulfilLengthRequirements"
      MERCURE_SUBSCRIBER_JWT_KEY: "!subscriberKeyOnlyForDevPaddingToFulfilLengthRequirements"
      OTEL_PHP_AUTOLOAD_ENABLED: true
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
      OTEL_SERVICE_NAME: webpage2kindle
#  consumer:
#    build:
#      context: ./symfony-app
#      dockerfile: Dockerfile
#    volumes:
#      - ./symfony-app:/app
#    depends_on:
#      - rabbitmq
#    command: [ "/app/bin/wait-for-it.sh", "rabbitmq:5672", "--", "php", "-d", "apc.enable_cli=1", "/app/bin/console", "rabbitmq:multiple-consumer", "-m", "10", "pipeline" ]
  node:
    build:
      context: ./node-readability
      dockerfile: Dockerfile-dev
    volumes:
      - ./node-readability:/app
    command: [ "npx", "tsx", "watch", "--import", "/app/instrument.mjs", "/app/microservice.ts" ]
    ports:
      - "3000:3000"
  rabbitmq:
    image: rabbitmq:3.9.5-management
    ports:
      - "5672:5672"
      - "15672:15672"
  go-readability-api:
    build:
      context: ./go-readability-api
      dockerfile: Dockerfile
    command:
      - --http
      - :8080
  redis:
      image: redis:7.0-alpine
  redis-web:
      image: rediscommander/redis-commander:latest
      environment:
          - REDIS_HOSTS=local:redis:6379
      ports:
        - "8081:8081"
  collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  jaeger:
      image: cr.jaegertracing.io/jaegertracing/jaeger:2.9.0
      ports:
        - 6831:6831/udp
        - 16686:16686 # Jaeger UI
