include: '/.gitlab/docker-template.yaml'

stages:
  - prepare
  - docker

public:
  stage: prepare
  image: thecodingmachine/php:8.1-v4-cli-node16
  script:
    - cp -r symfony-app/public caddy/public
  artifacts:
    paths:
      - caddy/public/
    expire_in: 30 days
    when: on_success

docker/main:
  extends: .docker
  dependencies:
    - public
  script:
    - >
      [[ "$CI_COMMIT_BRANCH" -eq "main" ]] && IMAGE_TAG=latest || IMAGE_TAG=`echo $CI_COMMIT_BRANCH  | tr ' /_' '-' | tr -cd 'a-zA-Z0-9-' | tr -s '-' `
    - echo "IMAGE_TAG - $IMAGE_TAG (CI_COMMIT_BRANCH - $CI_COMMIT_BRANCH)"
    - /kaniko/executor --context $CI_PROJECT_DIR/caddy --dockerfile $CI_PROJECT_DIR/caddy/Dockerfile --destination ${CI_REGISTRY}/${CI_PROJECT_PATH}/caddy:$IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "parent_pipeline"
      when: manual
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "push"
      when: manual
      allow_failure: true
