services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
        exclude: '../tests/Behat/bootstrap.php'

    prometheus_storage:
        class: Prometheus\Storage\InMemory

    App\Infrastructure\RabbitMq\InMemoryProducer:
        public: true
    App\Web\Infrastructure\Producer\RabbitMq\NewJobProducer:
        arguments:
            $producer: '@App\Infrastructure\RabbitMq\InMemoryProducer'

    App\Job\Domain\InMemoryJobProvider:
        public: true
    App\Job\Domain\JobProviderInterface: '@App\Job\Domain\InMemoryJobProvider'

    App\Infrastructure\SSE\InMemoryPublisher:
        public: true
    App\Domain\Contract\SSEPublisherInterface: '@App\Infrastructure\SSE\InMemoryPublisher'

    App\Job\PageContentFetcher\StaticPageContentFetcher: ~
    App\Job\PageContentFetcher\PageContentFetcherInterface: '@App\Job\PageContentFetcher\StaticPageContentFetcher'

    App\Job\PushToKindleUrlGenerator\FakePushToKindleUrlGenerator: ~
    App\Job\PushToKindleUrlGenerator\PushToKindleUrlGeneratorInterface: '@App\Job\PushToKindleUrlGenerator\FakePushToKindleUrlGenerator'

    App\Job\ReadablePageContent\StaticReadablePageContent: ~
    App\Job\ReadablePageContent\CreateReadablePageContentInterface: '@App\Job\ReadablePageContent\StaticReadablePageContent'
