services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'
        exclude: '../tests/Behat/bootstrap.php'

    prometheus_storage:
        class: Prometheus\Storage\InMemory

    App\Job\PageContentFetcher\StaticPageContentFetcher: ~
    App\Job\PageContentFetcher\PageContentFetcherInterface: '@App\Job\PageContentFetcher\StaticPageContentFetcher'

    App\Job\PushToKindleUrlGenerator\FakePushToKindleUrlGenerator: ~
    App\Job\PushToKindleUrlGenerator\PushToKindleUrlGeneratorInterface: '@App\Job\PushToKindleUrlGenerator\FakePushToKindleUrlGenerator'
