# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix']
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            go_readability_microservice.client:
                base_uri: '%env(GO_READABILITY_MICROSERVICE_URL)%'
            node_microservice.client:
                base_uri: '%env(NODE_MICROSERVICE_URL)%'
            push_to_kindle.client:
                base_uri: 'https://pastepad.fivefilters.org'
                max_redirects: 0
                headers:
                    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0'
                    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'
                    'Accept-Language': 'en-US,en;q=0.5'
                    'Content-Type': 'application/x-www-form-urlencoded'
                    'Origin': 'https://pastepad.fivefilters.org'
    rate_limiter:
        api:
            policy: 'token_bucket'
            limit: 30
            rate: { interval: '1 minute', amount: 10 }
            cache_pool: 'cache.rate_limiter_api'
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
