nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Extension-Version']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/web-extension':
          allow_origin: [ '*' ]
          allow_methods: [ 'POST' ]
          max_age: 3600
        '^/': null

when@dev:
  nelmio_cors:
    paths:
      '^/web-extension':
        allow_private_network: true