old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.<name>_producer' service to send data.
        new_job:
            class: App\Infrastructure\RabbitMq\ProducerRequestIdStamp
            connection:       default
            exchange_options: { name: 'pipeline', type: direct }
            default_content_type: 'application/json'
            default_routing_key: 'new_job'
        fetch_page_content:
            connection:       default
            exchange_options: { name: 'pipeline', type: direct }
            default_content_type: 'application/json'
            default_routing_key: 'fetch_page_content'
        push_to_kindle_url:
            connection:       default
            exchange_options: { name: 'pipeline', type: direct }
            default_content_type: 'application/json'
            default_routing_key: 'push_to_kindle_url'
    consumers:
        new_job:
            connection:       default
            exchange_options: { name: 'new_job', type: direct }
            queue_options:    { name: 'new_job'}
            callback:         App\Consumer\NewJobConsumer
        fetch_page_content:
            connection:       default
            exchange_options: { name: 'fetch_page_content', type: direct }
            queue_options:    { name: 'fetch_page_content'}
            callback:         App\Consumer\FetchPageContentConsumer
        push_to_kindle_url:
            connection:       default
            exchange_options: { name: 'push_to_kindle_url', type: direct }
            queue_options:    { name: 'push_to_kindle_url'}
            callback:         App\Consumer\CreatePushToKindleUrlConsumer
    multiple_consumers:
        pipeline:
            connection: default
            exchange_options: { name: 'pipeline', type: direct }
            queues:
                new_job:
                    name: new_job
                    callback: App\Consumer\NewJobConsumer
                    routing_keys:
                        - new_job
                fetch_page_content:
                    name: fetch_page_content
                    callback: App\Consumer\FetchPageContentConsumer
                    routing_keys:
                        - fetch_page_content
                push_to_kindle_url:
                    name: push_to_kindle_url
                    callback:  App\Consumer\CreatePushToKindleUrlConsumer
                    routing-keys:
                        - push_to_kindle_url
