old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.<name>_producer' service to send data.
        new_job:
            connection:       default
            exchange_options: { name: 'new_job', type: direct }
        fetch_page_content:
            connection:       default
            exchange_options: { name: 'fetch_page_content', type: direct }
        push_to_kindle_url:
            connection:       default
            exchange_options: { name: 'push_to_kindle_url', type: direct }
    consumers:
        new_job:
            connection:       default
            exchange_options: { name: 'new_job', type: direct }
            queue_options:    { name: 'new_job'}
            callback:         App\Consumer\NewJobConsumer
        fetch_page_content:
            connection:       default
            exchange_options: { name: 'fetch_page_content', type: direct }
            queue_options:    { name: 'fetch_page_content'}
            callback:         App\Consumer\FetchPageContentConsumer
        push_to_kindle_url:
            connection:       default
            exchange_options: { name: 'push_to_kindle_url', type: direct }
            queue_options:    { name: 'push_to_kindle_url'}
            callback:         App\Consumer\CreatePushToKindleUrlConsumer
