old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            connection_timeout: 3
            read_write_timeout: 120
            keepalive: true
    producers:
        # use 'old_sound_rabbit_mq.<name>_producer' service to send data.
        new_job:
            class: App\Infrastructure\RabbitMq\ProducerRequestIdStamp
            connection:       default
            exchange_options: { name: 'pipeline', type: direct }
            default_content_type: 'application/json'
            default_routing_key: 'new_job'
        fetch_page_content:
            connection:       default
            exchange_options: { name: 'pipeline', type: direct }
            default_content_type: 'application/json'
            default_routing_key: 'fetch_page_content'
        push_to_kindle_url:
            connection:       default
            exchange_options: { name: 'pipeline', type: direct }
            default_content_type: 'application/json'
            default_routing_key: 'push_to_kindle_url'
    consumers:
        failed:
            connection: default
            exchange_options: { name: 'failed-jobs', type: direct }
            queue_options: { name: 'failed-jobs', routing_keys: ['*'] }
            callback: App\Consumer\FailedJob
    multiple_consumers:
        pipeline:
            connection: default
            exchange_options: { name: 'pipeline', type: direct }
            queues:
                new_job:
                    name: new_job2
                    callback: App\Consumer\NewJobConsumer
                    routing_keys:
                        - new_job
                    arguments: {'x-dead-letter-exchange': ['S', 'failed-jobs'], 'x-message-ttl': ['I', 60000]} # 60 seconds
                fetch_page_content:
                    name: fetch_page_content2
                    callback: App\Consumer\FetchPageContentConsumer
                    routing_keys:
                        - fetch_page_content
                    arguments: {'x-dead-letter-exchange': ['S', 'failed-jobs'], 'x-message-ttl': ['I', 120000]} # 120 seconds
                push_to_kindle_url:
                    name: push_to_kindle_url2
                    callback:  App\Consumer\CreatePushToKindleUrlConsumer
                    routing-keys:
                        - push_to_kindle_url
                    arguments: {'x-dead-letter-exchange': ['S', 'failed-jobs'], 'x-message-ttl': ['I', 90000]} # 90 seconds
