# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Broadway\EventStore\Dbal\DBALEventStore: '@broadway.event_store.dbal'
    Broadway\CommandHandling\CommandBus: '@broadway.command_handling.event_dispatching_command_bus'
    Broadway\UuidGenerator\UuidGeneratorInterface: '@broadway.uuid.generator'
    Broadway\EventStore\EventStore: '@broadway.event_store.dbal'
    Broadway\EventHandling\EventBus: '@broadway.event_handling.event_bus'

    App\Job\JobCommandHandler:
        tags:
            - { name: broadway.command_handler }
    App\Job\Domain\JobRepository:
        arguments:
            $eventStreamDecorators:
              - '@broadway.metadata_enriching_event_stream_decorator'

    # prometheus metrics
    App\Job\PageContentFetcher\GoReadabilitySynchronousPageContentFetcher:
        arguments:
            $pathToCommand: '%env(GO_READABILITY_PATH)%'
    App\Job\PageContentFetcher\PrometheusMetricDecorator:
        arguments:
            $pageContentFetcher: '@App\Job\PageContentFetcher\GoReadabilitySynchronousPageContentFetcher'
            $prometheusAdapterLabel: 'GoReadability'
    App\Job\PageContentFetcher\PageContentFetcherInterface: '@App\Job\PageContentFetcher\PrometheusMetricDecorator'
    prometheus_storage:
        class: Prometheus\Storage\APC
    Prometheus\CollectorRegistry:
        class: Prometheus\CollectorRegistry
        arguments:
            $storageAdapter: '@prometheus_storage'
    Prometheus\RenderTextFormat: ~
    App\Controller\MetricController:
        tags: ['controller.service_arguments']
